cmd/deps: require `cask/cask`
Currently `brew deps` fails with the following error:
```
$ brew deps
Error: undefined method 'all' for class Cask::Cask
/opt/homebrew/Library/Homebrew/cmd/deps.rb:195:in 'block in Homebrew::Cmd::Deps#run'
/opt/homebrew/Library/Homebrew/simulate_system.rb:40:in 'Homebrew::SimulateSystem.with'
/opt/homebrew/Library/Homebrew/cmd/deps.rb:125:in 'Homebrew::Cmd::Deps#run'
/opt/homebrew/Library/Homebrew/brew.rb:142:in '<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```