Cask::Auditor: fix audit return type
When the `HOMEBREW_SORBET_RECURSIVE=1` environment variable is set,
running `brew audit` on a cask with audit errors will produce a type
error: `Return value: Expected type T::Set[String], got
T::Set[T::Hash[Symbol, T.nilable(T.any(String, T::Boolean))]]`. This
occurs because the `Cask::Auditor.audit` and `#audit` methods are
expected to return a Set of strings but the Set is populated with
`Cask::Audit::Error` objects, which is a type alias for a specific
hash structure. This updates the related return types to use
`T::Set[Audit::Error]`.