shared_audits: print repo age if too new
Repo creation date is usually not visible to end users, and the repo age is being calculated anyway.

Before:
```
% brew audit --new --fix usbtree
usbtree
  * GitHub repository too new (<30 days old)
Error: 1 problem in 1 formula detected.
```

After:
```
% brew audit --new --fix usbtree
usbtree
  * GitHub repository too new (29 days old, 30 days required)
Error: 1 problem in 1 formula detected.
```

Also fixes the incorrect age test for Bitbucket.