tests: Use full constant names sometimes (for Sorbet rule 5001 compat)
- After https://github.com/Homebrew/brew/pull/22307, I looked into what
  was needed to move the rest of the tests to Sorbet `typed: true` or
  higher.
- Running `spoom` in dry-run mode found that several files only had one
  error: using the new `klass` or `subject` variable as a dynamic
  constant, instead of the full constant name (that is,
  https://sorbet.org/docs/error-reference#5001).
- So, I got OpenAI Codex 5.3 Medium to bump all the specs to
  `typed: true`, search for only 5001 errors. There were 120 errors.
  Then for each of them I replaced `klass` or `subject` with the full
  constant name. Now a few more tests are typechecked to `true`, and
  we have less far to go on the others.