sandbox: scope `require "trust"` to avoid `brew irb` failure
This helps avoid an require loop resulting in
```
Error: uninitialized constant Cask::DSL::Artifact
```