cmd/uses: require `cask/cask`
Currently `brew uses` fails with the following error:
```
$ brew uses cmake
Error: undefined method 'all' for class Cask::Cask
/opt/homebrew/Library/Homebrew/cmd/uses.rb:137:in
'Homebrew::Cmd::Uses#intersection_of_dependents'
/opt/homebrew/Library/Homebrew/cmd/uses.rb:87:in
'Homebrew::Cmd::Uses#run'
/opt/homebrew/Library/Homebrew/brew.rb:142:in '<main>'
Please report this issue:
  https://docs.brew.sh/Troubleshooting
```

Signed-off-by: botantony <antonsm21@gmail.com>